### ISSUE TITLE
Program panicked at lib.rs:535:43

### ISSUE THREAD

**Issue by ZhoufangErqiangu** [project-serum/swap#26]
I have met an error as follow.

    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3297 of 179574 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24372 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program 22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'called `Option::unwrap()` on a `None` value', programs/swap/src/lib.rs:535:43
    Program 22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD consumed 14288 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program 22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD failed: Program failed to complete

I have checked the source code, the line 535 is as follow.

NonZeroU64::new(max_coin_qty).unwrap(),

'max_coin_qty' is a const.

It is very confuse how can this be error.

**Comment by ZhoufangErqiangu** [comment]
0x22 means the token amount in baseWallet and quoteWallet is not enough

**Comment by ZhoufangErqiangu** [comment]
0x12e means the amount is too small

**Comment by ZhoufangErqiangu** [comment]
0x12d is caused by apply risk check.
mostly, that means the exchange rate is too big.

**Comment by ZhoufangErqiangu** [comment]
panicked at line 535 is caused by lot size error.
that means the amount is too small

**Comment by ZhoufangErqiangu** [comment]
the amount is base mint amount, not quote amount.
the rate number must mul quote decimals.
